version: '3.9'

services:
  api:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    volumes:
      - ./src/:/code/
    ports:
      - 8002:8000
    env_file:
      - envs/.docker.env
    depends_on:
      - database
    
  database:
    image: postgres:15-alpine
    env_file:
      - envs/.docker.env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
